In [1]:
# Importing Libraries
import selenium
import pandas as pd
import time
from bs4 import BeautifulSoup

# Importing selenium webdriver 
from selenium import webdriver

# Importing required Exceptions which needs to handled
from selenium.common.exceptions import StaleElementReferenceException, NoSuchElementException

#Importing requests
import requests


# importing regex
import re
from selenium.common.exceptions import StaleElementReferenceException, NoSuchElementException, ElementNotVisibleException, ElementNotInteractableException, SessionNotCreatedException, TimeoutException

In [2]:
#Lets first connect to the web drivers
driver=webdriver.Chrome(r"C:\Users\G\Downloads\chromedriver_win32\chromedriver.exe")

In [3]:
driver.get("https://www.naukri.com/")
time.sleep(3)

In [4]:
#clickng on top web page secarch bar option 
job_srch = input('Enter job name : ')                                         # Enter JOB to be searched
search = driver.find_element_by_id("qsb-keyword-sugg")                       # JOB search bar
search.clear()                                                             # clearing search bar
time.sleep(2)

loct_srch = input('Enter loction job : ')                                         # Enter LOCTION to be searched
search1 = driver.find_element_by_id("qsb-location-sugg")                       # locating search bar
search1.clear()                                                             # clearing search bar
time.sleep(2)




search.send_keys(job_srch)                                                     # entering values in search bar
search1.send_keys(loct_srch)
button = driver.find_element_by_xpath("//div[@class='search-btn']")               # locating search button
button.click()                                                             # clicking search button
time.sleep(3)

Enter job name : data scientist
Enter loction job : delhi

In [10]:
#intialising lists
designation = []
company = []
skill = []
loction=[]

In [13]:
#designation
designations=driver.find_elements_by_xpath("//a[@class='title fw500 ellipsis']")
for i in designations:
    designation.append(i.text)

In [16]:
#comapany
companys=driver.find_elements_by_xpath("//a[@class='subTitle ellipsis fleft']")
for i in companys:
    company.append(i.text)

In [19]:
#Location
loctions=driver.find_elements_by_xpath("//li[@class='fleft grey-text br2 placeHolderLi location']")
for i in loctions:
    loction.append(i.text)

In [21]:
#skill
skills=driver.find_elements_by_xpath("//li[@class='fleft fs12 grey-text lh16 dot']")
for i in skills:
    skill.append(i.text)

In [23]:
df=pd.DataFrame({})
df["designations"]=designation[0:20]
df["companys"]=company[0:20]
df["skills"]=skill[0:20]
df["loctions"]=loction[0:20]

df

,designations,companys,skills,loctions
0,Senior Data Scientist | CES IT LTD | CMMI Level 5,CES Ltd.,IT Skills,"Chennai, Pune, Delhi NCR, Mumbai, Bengaluru, H..."
1,Associate Data Scientist | 0-2 Years | Gurgaon,Xtage Technologies Private Limited,Python,"Delhi NCR, Gurgaon"
2,Data Scientist,Country Veggie,Tensorflow,"Ghaziabad, Bhopal, Lucknow, Kanpur, Rajkot, Be..."
3,Data Scientist,IBM India Pvt. Limited,Object Detection,Gurgaon Gurugram
4,Data Scientist,IBM India Pvt. Limited,Algorithm Development,Gurgaon Gurugram
5,Senior Data Scientist (Remote / Work from Home),Wallethub,Analytical Skills,"Chennai, Delhi NCR, Bengaluru"
6,Founding Member & Principal Data Scientist,Benovymed Healthcare,Programming,Gurgaon Gurugram
7,Data Scientist,Amantya Technologies,Machine Learning,Gurgaon
8,Analyst/Senior Analyst - DATA Scientist,Tredence,Advanced Analytics,"Chennai, Delhi NCR, Bengaluru"
9,Senior/Lead Data Scientist,Editorialist YX India Private Limited,Statistics,"Delhi NCR, Gurgaon"
10,Senior Data Scientist,Chegg India Pvt Ltd,Machine Learning,Delhi
11,Senior Data Scientist - Computer Vision,IRIS SOFTWARE Inc,IT Skills,Delhi NCR
12,Data Scientist/Analyst - Machine Learning/Deep...,EchoIndia,Python,Delhi
13,Data Scientist - Machine Learning/NLP,TalPro,Data Science,Gurgaon Gurugram
14,Only Fresher / Data Scientist / Data Analyst /...,GABA Consultancy services,Machine Learning,"Delhi NCR, Noida, Gurgaon"
15,Data Scientist opening at Saarthee Technology ...,Saarthee Technology Pvt Ltd,Python,Gurgaon
16,Data Scientist,Splash M,PDF,Gurgaon
17,Data Scientist,Agreeya,Data management,Gurgaon
18,Data Scientist,Ciena,data science,Gurgaon Gurugram
19,Lead Data Scientist | ML & Advanced Analytics ...,Xtage Technologies Private Limited,Machine learning,"Delhi NCR, Gurgaon"